# Generated by Django 3.0.7 on 2020-07-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200704_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(default='#', max_length=400),
        ),
    ]
